services:
  - type: web
    name: multivendor-store
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        value: https://multivendor-store-kykr.onrender.com
      - key: ASSET_URL
        value: https://multivendor-store-kykr.onrender.com
      - key: APP_KEY
        value: "base64:+RLH70IXwcygyDPZGH0Euo2e4FK8G2WO+Q7QfRjBzxE="
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
